### ISSUE TITLE
MAAP (whatever features hidden in DAAP it should be hidden in MAAP to)

### ISSUE THREAD

**Issue by Mseenu** [GanuM/profitGuruPOS#342]
- [ ] customer: - should be hide " eligible for loyalty "
- [ ] item :- should be hide " eligible for loyalty "
- [ ] report:-  in detailed report:-
     1. customer :- hide "export to excle"
     2.employee :- hide "export to excel"
     - [ ] in inventory report : -
         1.low inventory :- hide "export to excel"
         2.inventory summary :-hide "export to excel"
- [x] store configuration : - enabled the followimg settings
       1.storage setting
       2.receipt setting
- [ ] hide " DB and TM "

**Comment by vijaychhetry** [comment]
fixed..

**Comment by dharwadkarR** [comment]
This are still exists 
- [ ] view  customer: - should be hide " eligible for loyalty "
- [ ] view 2.receipt setting
- [ ] hide " DB and TM "

**Comment by vijaychhetry** [comment]
please add more details which page  or add screenshot
